### ISSUE TITLE
Problems using csvdupe and running nosetests 

### ISSUE THREAD

**Issue by DaveKlassen4** [datamade/csvdedupe#40]
I have come across this issue in many attempts to use the script. In the most recent case I cloned this repo (and dedupe) and followed the "Testing" instructions in the README files. Completing the tests for dedupe did not surface any issues, however testing csvdedupe produced this output:

	[user@localhost csvdedupe]# nosetests
	....E.....
	======================================================================
	ERROR: test_no_training (test_command_line.TestCSVDedupe)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python3.4/site-packages/pexpect/spawnbase.py", line 144, in read_nonblocking
		s = os.read(self.child_fd, size)
	OSError: [Errno 5] Input/output error

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/lib/python3.4/site-packages/pexpect/expect.py", line 97, in expect_loop
		incoming = spawn.read_nonblocking(spawn.maxread, timeout)
	  File "/usr/lib/python3.4/site-packages/pexpect/pty_spawn.py", line 455, in read_nonblocking
		return super(spawn, self).read_nonblocking(size)
	  File "/usr/lib/python3.4/site-packages/pexpect/spawnbase.py", line 149, in read_nonblocking
		raise EOF('End Of File (EOF). Exception style platform.')
	pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/user/src/csvdedupe/tests/test_command_line.py", line 26, in test_no_training
		child.expect("error: You need to provide an existing training_file or run this script without --skip_training")
	  File "/usr/lib/python3.4/site-packages/pexpect/spawnbase.py", line 315, in expect
		timeout, searchwindowsize, async)
	  File "/usr/lib/python3.4/site-packages/pexpect/spawnbase.py", line 339, in expect_list
		return exp.expect_loop(timeout)
	  File "/usr/lib/python3.4/site-packages/pexpect/expect.py", line 102, in expect_loop
		return self.eof(e)
	  File "/usr/lib/python3.4/site-packages/pexpect/expect.py", line 49, in eof
		raise EOF(msg)
	pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
	<pexpect.pty_spawn.spawn object at 0x7f4d16efa860>
	command: /bin/csvdedupe
	args: ['/bin/csvdedupe', 'examples/csv_example_messy_input.csv', '--field_names', 'Site name', 'Address', 'Zip', 'Phone', '--training_file', 'foo.json', '--skip_training']
	searcher: None
	buffer (last 100 chars): b''
	before (last 100 chars): b'ltiprocessing/pool.py", line 599, in get\r\n    raise self._value\r\nZeroDivisionError: float division\r\n'
	after: <class 'pexpect.exceptions.EOF'>
	match: None
	match_index: None
	exitstatus: None
	flag_eof: True
	pid: 6063
	child_fd: 6
	closed: False
	timeout: 30
	delimiter: <class 'pexpect.exceptions.EOF'>
	logfile: None
	logfile_read: None
	logfile_send: None
	maxread: 2000
	ignorecase: False
	searchwindowsize: None
	delaybeforesend: 0.05
	delayafterclose: 0.1
	delayafterterminate: 0.1

	----------------------------------------------------------------------
	Ran 10 tests in 50.870s

	FAILED (errors=1)

The error reported:

	ZeroDivisionError: float division

is the exact same error I received when first attempting to execute against my own csv file. A better traceback of the problem occurs when I run this command:

	[user@localhost deduper]$ csvdedupe examples/csv_example_messy_input.csv --field_names "Site name" Address Zip Phone --output_file output.csv
	INFO:root:imported 3337 rows
	INFO:root:using fields: ['Site name', 'Address', 'Zip', 'Phone']
	INFO:root:taking a sample of 1500 possible pairs
	multiprocessing.pool.RemoteTraceback:
	"""
	Traceback (most recent call last):
	  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 119, in worker
		result = (True, func(*args, **kwds))
	  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 44, in mapstar
		return list(map(*args))
	  File "/usr/lib64/python3.4/site-packages/dedupe/datamodel.py", line 83, in distances
		record_2[field])
	  File "affinegap/affinegap.pyx", line 115, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1788)
	  File "affinegap/affinegap.pyx", line 134, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1615)
	ZeroDivisionError: float division
	"""

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/usr/bin/csvdedupe", line 11, in <module>
		sys.exit(launch_new_instance())
	  File "/usr/lib/python3.4/site-packages/csvdedupe/csvdedupe.py", line 162, in launch_new_instance
		d.main()
	  File "/usr/lib/python3.4/site-packages/csvdedupe/csvdedupe.py", line 86, in main	
		deduper.sample(data_d, self.sample_size)
	  File "/usr/lib64/python3.4/site-packages/dedupe/api.py", line 931, in sample
		self._loadSample(data_sample)
	  File "/usr/lib64/python3.4/site-packages/dedupe/api.py", line 873, in _loadSample
		self.num_cores)
	  File "/usr/lib64/python3.4/site-packages/dedupe/training.py", line 52, in __init__
		2))
	  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 260, in map
		return self._map_async(func, iterable, mapstar, chunksize).get()
	  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 599, in get
		raise self._value
	ZeroDivisionError: float division

I have encountered the errors using python2.7 and python 3.4 on a centos7 VM, cygwin, and Python4Windows. In each instance I have managed to get numpy to install. Since the error appears to have ended in the multiprocessing libraries. perhaps I have not properly configured python? However I have tried many different combinations already. Any hints around how I can execute this test successfully?:

csvdedupe examples/csv_example_messy_input.csv --field_names "Site name" Address Zip Phone --output_file output.csv

**Comment by DaveKlassen4** [comment]
Perhaps I have stumbled upon a real problem, given I was able to make this work, however I also supposed it could easily be the case that I do not truly understand the authors intentions. In my most recent scenario of working with sample data, I slightly modified the config file "csvdeupe/examples/config.json.example" changing:


	field_definition   to   field_definitions


I then modified the file datamodel.py in the dedupe distribution like so:


	[user@localhost dedupe]# diff dedupe/dedupe/datamodel.py datamodel.py

	81c81
	<                 if record_1[field] is not None and record_2[field] is not None :
	---
	>                 if (record_1[field] is not None and record_2[field] is not None) and (record_1[field] is not "" and record_2[field] is not "") :


Finally when I run the command:


	csvdedupe examples/csv_example_messy_input.csv --config_file=examples/config.json.example


I successfully execute the program, and I am prompted to review like entries. From a experience point of view the scripts seem to be working without fail, but in terms of a working as expected "judgement", I do not believe I am the best judge of the authors intentions. Feel free to comment.

**Comment by DaveKlassen4** [comment]
A final comment... this does not solve the 'nosetests' issue, because the failed case never did specify any "Has Missing" field_defintions', and in that case perhaps test failure is the expected case.

**Comment by fgregg** [comment]
Fixed by https://github.com/datamade/csvdedupe/commit/7e793ff8db28c7957473209940f48983e0c731dc

**Comment by DaveKlassen4** [comment]
Thanks that solved the nosetest, but did not solve the problem loading my training data. I will try to hunt down the code required to prevent this in loading my training data.

**Comment by hammady** [comment]
@DaveKlassen4 the patch your wrote should be:

    if (record_1[field] is not None and record_2[field] is not None) and (record_1[field] != "" and record_2[field] != "") :

Note the use of `!= ""` rather than `is not`

This solves the problem of missing values in my training data.
